name: disposable_container
description: A flutter package that manages dispose callbacks and subscriptions cancellations.
version: 0.0.3
homepage: https://github.com/spideythewebhead/disposable_container

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.2
  flutter_lints: ^2.0.1

flutter:
