name: disposable_container
description: A flutter package that manages dispose callbacks and subscriptions cancellations.
version: 0.1.0
homepage: https://github.com/spideythewebhead/disposable_container

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1

flutter:
