name: Publish Workflow

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.1"
          channel: "stable"
      - run: flutter pub get
      - run: dart format --output none --set-exit-if-changed -l 80 lib
      - run: dart analyze --fatal-infos --fatal-warnings lib
      - run: flutter test
      - name: Release
        run: |
          dart pub publish --dry-run
          mkdir -p ~/.config/dart
          echo "${{ secrets.PUBDEV_TOKEN }}" | base64 --decode >> ~/.config/dart/pub-credentials.json
          dart pub publish --force
